# Variables to inject into Java variables
ebayTokenUrl: ${EBAY_TOKEN_URL:https://api.ebay.com/identity/v1/oauth2/token}
principalRoleName: ${PRINCIPAL_ROLE_NAME}

logging:
  level:
    root: warn
server:
  port: ${SERVER_PORT:8000}
spring:
  application:
    name: ebay-user-auth-service
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_URI}/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
  devtools:
    livereload:
      port: ${LIVERELOAD_PORT:35730}
      enabled: true
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URL}
          opaquetoken:
            client-id: ${OAUTH2_PROVIDER_CLIENT_ID}
            client-secret: ${OAUTH2_PROVIDER_CLIENT_SECRET}
            introspection-uri: ${OAUTH2_PROVIDER_INTROSPECTION_URL}
