CREATE TABLE user_auth_code_entity
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    auth_code          VARCHAR(255),
    expires_in         INTEGER,
    creation_date      date,
    creation_time      time WITHOUT TIME ZONE,
    creation_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_userauthcodeentity PRIMARY KEY (id)
);