CREATE TABLE user_access_token_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    expires_in    INTEGER,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    access_token  VARCHAR(2560),
    CONSTRAINT pk_useraccesstokenentity PRIMARY KEY (id)
);

CREATE TABLE user_refresh_token_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    expires_in    INTEGER,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    refresh_token VARCHAR(255),
    CONSTRAINT pk_userrefreshtokenentity PRIMARY KEY (id)
);